server {
    listen 80;
    server_name localhost;
    resolver 127.0.0.11 10.43.0.10 valid=10s ipv6=off;


    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /auth/ {
        set $game_upstream http://game-server.game.svc.cluster.local:4000;
        proxy_pass $game_upstream/api/auth/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/account/ {
        set $account_upstream http://account-service.identity.svc.cluster.local:4005;
        proxy_pass $account_upstream/api/account/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/quiz/ {
        set $quiz_upstream http://quiz-service.quiz.svc.cluster.local:4001;
        proxy_pass $quiz_upstream/api/quiz/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        set $game_api_upstream http://game-server.game.svc.cluster.local:4000;
        proxy_pass $game_api_upstream/api/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /socket.io/ {
        set $game_ws_upstream http://game-server.game.svc.cluster.local:4000;
        proxy_pass $game_ws_upstream/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
