---
k8s_namespace: "game"
quiz_image: "docker.io/library/tank-quiz-service:latest"
client_image: "docker.io/library/tank-game-client:latest"
server_image: "docker.io/library/tank-game-server:latest"
tar_quiz_path: "/tmp/tank-quiz-service.tar"
tar_client_path: "/tmp/tank-game-client.tar"
tar_server_path: "/tmp/tank-game-server.tar"
domain_host: "tank.192-168-50-96.sslip.io"
jwt_secret: "tank-battle-quiz-secret-2026"
